[programs.localnet]
chainwork = "BKrfKJSFgPP1jvAZDLxQymwQYov8ktZntVdE9TBLHrLr"

[programs.devnet]
chainwork = "BKrfKJSFgPP1jvAZDLxQymwQYov8ktZntVdE9TBLHrLr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
